/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Song;
import java.lang.UnsupportedOperationException;

public class App {
    public static void main(String[] args) {
        int from = Integer.parseInt(args[0]);
        int to = Integer.parseInt(args[1]);
        System.out.println(verses(from, to));
    }

    public static String verses(int from, int to) {
        String song = "";
        for (int i = to; i < from + 1; i++) {
            int currentNb = from - i;
            song += verse(currentNb);
        }

        return song;
    }

    public static String verse(int number) {
        Bottle bottle = Bottle.factory(number);
        Bottle successor = Bottle.successor(number);

        if (number >= 0  && number < 100) {
            return
                    Bottle.capitalize(bottle.remaining()) + " " + bottle.containers() + " of beer on the wall, " + bottle.remaining() + " " + bottle.containers() + " of beer.\n"
                            + bottle.action() + " " + successor.remaining() + " " + successor.containers() + " of beer on the wall.\n";
        } else {
            throw new UnsupportedOperationException();
        }
    }
}
