/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Song;

public class App {
    public static void main(String[] args) {
        int from = Integer.parseInt(args[0]);
        int to = Integer.parseInt(args[1]);
        System.out.println(new Bottle().verses(from, to));
    }
}
